version: "2"
run:
  tests: false
linters:
  default: all
  enable:
    - wsl_v5
  disable:
    - wsl
    - noinlineerr
    - depguard
    - exhaustruct
    - ireturn
    - lll
    - musttag
    - perfsprint
    - tagalign
    - varnamelen
  settings:
    govet:
      disable:
        - fieldalignment
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
