name: Cleanup old workflow runs

on:
  schedule:
    - cron: '0 0 * * *' # daily at midnight
  workflow_dispatch: # allow manual trigger

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      actions: write
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 3
          keep_minimum_runs: 1
